CREATE TABLE dataset
(
	Accident_Index TEXT,
	Location_Easting_OSGR TEXT,
	Location_Northing_OSGR TEXT,
	Longitude TEXT,
	Latitude TEXT,
	Police_Force TEXT,
	Accident_Severity TEXT,
	Number_of_Vehicles TEXT,
	Number_of_Casualties TEXT,
	Date TEXT,
	Day_of_Week TEXT,
	Time TEXT,
	Local_Authority_District TEXT,
	Local_Authority_Highway TEXT,
	first_Road_Class TEXT,
	first_Road_Number TEXT,
	Road_Type TEXT,
	Speed_limit TEXT,
	Junction_Detail TEXT,
	Junction_Control TEXT,
	second_Road_Class TEXT,
	second_Road_Number TEXT,
	Pedestrian_Crossing_Human_Control TEXT,
	Pedestrian_Crossing_Physical_Facilities TEXT,
	Light_Conditions TEXT,
	Weather_Conditions TEXT,
	Road_Surface_Conditions TEXT,
	Special_Conditions_at_Site TEXT,
	Carriageway_Hazards TEXT,
	Urban_or_Rural_Area TEXT,
	Did_Police_Officer_Attend_Scene_of_Accident TEXT,
	LSOA_of_Accident_Location TEXT
);
